"""add index to post table

Revision ID: 5577bbd80ee2
Revises: 49173e4648b3
Create Date: 2025-04-07 16:49:41.270649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5577bbd80ee2"
down_revision: Union[str, None] = "49173e4648b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_post_user_id"), "post", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_user_id"), table_name="post")
    # ### end Alembic commands ###
